### ISSUE TITLE
Error occurred while running MySQL statement

### ISSUE THREAD

**Issue by Elutri** [fl0gic/Up2Date#23]
25.06 23:31:06 [Server] ERROR ============== END ERROR ==============
25.06 23:31:06 [Server] WARN at java.lang.Thread.run(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
25.06 23:31:06 [Server] WARN at com.gamerking195.dev.up2date.update.UpdateManager.lambda$refresh$2(UpdateManager.java:310)
25.06 23:31:06 [Server] WARN at com.gamerking195.dev.up2date.update.UpdateManager.removeLinkedPlugin(UpdateManager.java:353)
25.06 23:31:06 [Server] WARN at com.gamerking195.dev.up2date.util.UtilSQL.runStatement(UtilSQL.java:61)
25.06 23:31:06 [Server] WARN at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
25.06 23:31:06 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
25.06 23:31:06 [Server] WARN java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@77377b95 rejected from java.util.concurrent.ThreadPoolExecutor@6c4b4081[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 2107]
25.06 23:31:06 [Server] ERROR STACKTRACE: 
25.06 23:31:06 [Server] ERROR MESSAGE: Task java.util.concurrent.FutureTask@77377b95 rejected from java.util.concurrent.ThreadPoolExecutor@6c4b4081[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 2107]
25.06 23:31:06 [Server] ERROR PLUGIN MESSAGE: Error occurred while running MySQL statement.
25.06 23:31:06 [Server] ERROR PLUGIN VERSION: V1.4.4 (LATEST)
25.06 23:31:06 [Server] ERROR ============== BEGIN ERROR ==============
25.06 23:31:06 [Server] INFO Or on spigot at https://spigotmc.org/threads/284883/
25.06 23:31:06 [Server] INFO If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/Up2Date/issues.
25.06 23:31:06 [Server] INFO A severe error has occurred with the Up2Date plugin.

**Comment by fl0gic** [comment]
Hey there, this is a known issue and I should have a fix coming out for it next week when I'm back from vacation.

**Comment by fl0gic** [comment]
Hello again, this has been addressed in version 1.5.1 found [here](https://www.spigotmc.org/resources/up2date.49313/update?update=235042). Please do not hesitate to contact me again in the future should more issues arise.
